# Model Parameters
gamma: null
learning_rate: 3e-6
lr_step_size: 1
batch_size: 32
        
# Model Architecture
         

## Dropouts
video_dropout: 0.3
force_dropout: 0.3 # Not used
width_dropout: 0.3 # Not used
est_dropout: 0.3
decoder_dropout: 0.3

##Feature Sizes
img_feature_size: 128
fwe_feature_size: 32 # Both force and width. Always one fully connected layer
decoder_size: [512, 512, 128] 
est_decoder_size: [64, 64, 32] 
decoder_output_size: 3

random_state: 42