gamma: 0.975
learning_rate: 0.00001
batch_size: 64
lr_step_size: 1 
random_state: 42 

# Model Architecture
## Dropout
lstm_dropout: 0.1
## Feature Sizes 
input_dim: 4096 # VGG16 fc7 do not change
hidden_dim: 128

scalar1_dim: 32
scalar2_dim: 32       
scalar3_dim: 32       
scalar4_dim: 32